---
title: "Grupo 9 - TP1"
author: "Angelina Garnica, Marcelo Costamagna, Selva LLanes"
date: "April 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("readr")
library("knitr")
library("data.table")
library("openxlsx")
```

```{r message=FALSE, warning=FALSE}
hfi_cc_2018 <- read_csv("../Data/hfi_cc_2018.csv")
```


## 1. Estadísticos Descriptivos


### 1.Para comenzar con un pantallazo de los datos, calcular el rango de las variables

```{r cars, message=FALSE, warning=FALSE, include=FALSE}
hfi <- hfi_cc_2018[, c(1:4, 53:61, 119:122)]

T0 <- hfi %>%
  group_by(countries) %>%
  summarise_all(mean, na.rm = T)
T1 <- hfi %>%
  group_by(countries) %>%
  summarise(q = n())
T2 <- hfi %>%
  group_by(region, year) %>%
  summarise_all(mean, na.rm = T)
```

```{r}

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
